Optimization
deathbaba/landing-php pull request #30
Opened 2017-03-01 04:50 UTC by aliakseimaniuk

2017-03-01 05:23 UTC, biodranik requested changes

2017-03-01 05:23 UTC, deathbaba commented on generate.php
> +  } else {
Однострочники решил делать с фигурными скобками? Везде же по коду я писал в одну строку, сейчас у нас уже два разных стиля в коде )

2017-03-01 05:23 UTC, deathbaba commented on generate.php
> +  $sitemapFullPath = $outDir . DIRECTORY_SEPARATOR . 'sitemap.xml';
Этот код дублируется и тут и ниже, имеет смысл вынести в функцию типа FullPathTo('sitemap.xml');

2017-03-01 05:23 UTC, deathbaba commented on generate.php
> +  file_put_contents($sitemapFullPath, $sitemapXml);
Ну и сделать однострочник file_put_contents(FullPathTo('sitemap.xml'), BuildSiteMapXml());

2017-03-01 05:23 UTC, deathbaba commented on include/globals.php
> +    if (array_key_exists('link', $props)) {
Не думаю, что нужна эта проверка. Нужно индексировать все страницы, которые в $PAGES, а link задумывался для красоты и удобства. Т.е. если линка нет, например, линк может быть по-умолчанию как имя php файла.

2017-03-01 14:07 UTC, aliakseimaniuk commented on include/globals.php
> +    if (array_key_exists('link', $props)) {
я сделал это чтобы спрятать 404.php, думаешь стоит эту страницу в сайт мэп добавлять?

2017-03-01 14:27 UTC, deathbaba commented
Это было не очевидно ) Конечно не стоит добавлять 404.
Добавь комментарий тогда, что этот иф фильтрует 404. А на будущее для 404 сделаем специальную логику, это же всё-таки действительно специальная страница.

2017-03-01 14:45 UTC, aliakseimaniuk commented
тогда без такой проверки не обойтись.

2017-03-01 14:48 UTC, aliakseimaniuk commented
Когда я пробегаю по pages массиву, мне надо понимать, какие элементы в sitemap отправлять. Можно было сделать какой нить другой флаг, но я решил так не делать, потому что link проперти достаточно.

2017-03-01 14:49 UTC, deathbaba commented
То, что ты пишешь - теперь уже понятно. Просто добавь комментарий перед ифом, зачем нужен этот иф.

2017-03-01 14:52 UTC, aliakseimaniuk commented
ок

2017-03-02 05:37 UTC, deathbaba commented on generate.php
> +  return $outDir . DIRECTORY_SEPARATOR . $fileName;
Тут не нужна ли защита от дурака, проверка на то, что outDir уже заканчивается на слеш?

2017-03-02 16:31 UTC, aliakseimaniuk commented on generate.php
> +  return $outDir . DIRECTORY_SEPARATOR . $fileName;
можно сделать

2017-03-03 03:33 UTC, merged